# golangci-lint configuration v2
# Strict configuration for production-quality Go code

version: "2"

run:
  # Timeout for analysis
  timeout: 5m
  # Include test files
  tests: true

linters:
  # Enable additional linters for stricter checks
  enable:
    # Bug detection
    - bodyclose          # HTTP response body not closed
    - contextcheck       # Non-inherited context usage
    - durationcheck      # Duration multiplication issues
    - errchkjson         # JSON encoding error checks
    - nilerr             # Returns nil even when error is not nil
    - nilnesserr         # Returns different nil value error
    - rowserrcheck       # sql.Rows.Err not closed
    - sqlclosecheck      # sql.Rows not closed
    
    # Code quality
    - gocritic           # Bugs, performance, style issues
    - goconst            # Repeated strings -> constants
    - gocognit           # Cognitive complexity
    - gocyclo            # Cyclomatic complexity
    - nestif             # Deeply nested if statements
    
    # Style & consistency
    - misspell           # Spelling errors
    - unconvert          # Unnecessary type conversions
    - unparam            # Unused function parameters
    - wastedassign       # Wasted assignments
    
    # Error handling
    - errorlint          # Error wrapping issues (Go 1.13+)
    
    # Performance
    - prealloc           # Slice preallocation suggestions
    - copyloopvar        # Loop variable copy issues
    
    # Maintainability
    - nakedret           # Naked returns in long functions
    
  # Disabled linters (too noisy or not applicable)
  disable:
    - wrapcheck          # Too many false positives for internal packages
    - noctx              # Conflicts with echo framework patterns
    - revive             # Too many style opinions
    - funlen             # Some long functions are acceptable (migrations, seeds)
    - maintidx           # Maintainability index is subjective
    - gosec              # Security linter - disabled globally, can be enabled for production code only

linters-settings:
  gocyclo:
    # Maximum cyclomatic complexity
    min-complexity: 15

  gocognit:
    # Maximum cognitive complexity
    min-complexity: 30

  funlen:
    # Maximum function length (increased from 60/40 to be less strict)
    lines: 120
    statements: 80

  nestif:
    # Maximum nesting level
    min-complexity: 5

  goconst:
    # Minimum string length for goconst
    min-len: 3
    # Minimum occurrences (increased to reduce noise)
    min-occurrences: 5

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam
      - exitAfterDefer  # We manually close resources before log.Fatalf

  gosec:
    excludes:
      - G104  # We handle some errors intentionally with _ =
      - G304  # File path from variable (common in web apps)
      - G102  # Bind to all interfaces (needed for test servers)
      - G204  # Subprocess with variable (needed for build/test tooling)
      - G301  # Directory permissions (0755 is acceptable)

  errcheck:
    # Check type assertions
    check-type-assertions: true
    # Check blank identifier assignments
    check-blank: false

  revive:
    # Only enable key rules, not all of them
    rules:
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  nakedret:
    # No naked returns in functions longer than this
    max-func-lines: 30

  maintidx:
    # Minimum maintainability index (0-100, higher is better)
    under: 15

  wrapcheck:
    # Ignore wrapped errors for common patterns
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    # Ignore packages that handle errors properly
    ignorePackageGlobs:
      - github.com/gti/heatmap-internal/internal/*

  misspell:
    locale: US

  noctx:
    # Don't require context for HTTP handlers (they have c.Request().Context())
    require-specific: true

issues:
  # Maximum issues per linter (0 = unlimited)
  max-issues-per-linter: 50
  # Maximum same issues (0 = unlimited)
  max-same-issues: 10
  
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec

    # E2E test infrastructure - exclude security and complexity checks
    - path: e2e/
      linters:
        - gosec
        - gocognit
        - gocyclo
        - contextcheck
        - nestif

    # Generated files (swagger docs)
    - path: docs/
      linters:
        - all
    
    # Allow complex logic in capacity handler (form parsing)
    - path: internal/handler/capacity\.go
      text: "cognitive complexity"
      linters:
        - gocognit
    
    - path: internal/handler/capacity\.go
      text: "complex nested blocks"
      linters:
        - nestif
    
    # exitAfterDefer is a false positive - we close DB before Fatalf
    - path: cmd/server/main\.go
      text: "exitAfterDefer"
      linters:
        - gocritic
